# Generated by Django 5.2.17 on 2026-09-21 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actor_label",
                    models.CharField(
                        blank=True,
                        help_text="Who acted, kept verbatim so the trail survives account deletion.",
                        max_length=254,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Created"),
                            ("update", "Updated"),
                            ("delete", "Deleted"),
                            ("login", "Signed in"),
                            ("login_failed", "Failed sign-in"),
                        ],
                        max_length=20,
                    ),
                ),
                ("object_type", models.CharField(blank=True, max_length=100)),
                ("object_id", models.CharField(blank=True, max_length=64)),
                ("object_label", models.CharField(blank=True, max_length=255)),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Field-level before/after values. Never holds payment details.",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["object_type", "object_id"],
                        name="core_audite_object__bbabc4_idx",
                    )
                ],
            },
        ),
    ]
