# Generated by Django 5.2.17 on 2026-09-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Created"),
                    ("update", "Updated"),
                    ("delete", "Deleted"),
                    ("login", "Signed in"),
                    ("login_failed", "Failed sign-in"),
                    ("export", "Exported"),
                ],
                max_length=20,
            ),
        ),
    ]
