# Generated by Django 5.2.17 on 2026-09-22 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentplan",
            name="stripe_schedule_id",
        ),
        migrations.RemoveField(
            model_name="scheduledpayment",
            name="stripe_invoice_id",
        ),
        migrations.AddField(
            model_name="paymentplan",
            name="stripe_payment_method_id",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="scheduledpayment",
            name="stripe_payment_intent_id",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
