# Generated by Django 5.2.17 on 2026-09-23 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_remove_paymentplan_stripe_schedule_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="terms_accepted_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="When the guest ticked to accept the published booking terms online.",
                null=True,
            ),
        ),
    ]
