# Generated by Django 5.2.17 on 2026-09-21 07:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PickupPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                (
                    "region",
                    models.CharField(
                        blank=True, help_text="State or province.", max_length=100
                    ),
                ),
                ("map_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["city", "name"],
            },
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("day_trip", "Day trip"),
                            ("overnight", "Overnight tour"),
                            ("theatre", "Theatre coach"),
                            ("luncheon", "Luncheon show"),
                            ("cruise", "Cruise"),
                            ("fly", "Fly tour"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        help_text="One or two lines shown on listings.", max_length=300
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="The full write-up shown on the trip page."
                    ),
                ),
                (
                    "inclusions",
                    models.TextField(
                        blank=True,
                        help_text="What the price covers, one item per line.",
                    ),
                ),
                (
                    "exclusions",
                    models.TextField(
                        blank=True,
                        help_text="What it does not cover, one item per line.",
                    ),
                ),
                ("meals_included", models.PositiveSmallIntegerField(default=0)),
                (
                    "terms",
                    models.TextField(
                        blank=True, help_text="Booking terms shown before payment."
                    ),
                ),
                ("hero_image", models.ImageField(blank=True, upload_to="trips/")),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Unpublished trips are invisible to guests, dates and all.",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
                "indexes": [
                    models.Index(
                        fields=["category", "is_published"],
                        name="catalog_tri_categor_9dd1d0_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Departure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateField(db_index=True)),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open for booking"),
                            ("waitlist", "Waitlist only"),
                            ("closed", "Closed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "capacity",
                    models.PositiveSmallIntegerField(
                        help_text="Total seats on the coach.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "seats_held_back",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Seats kept off the website for phone bookings and escorts.",
                    ),
                ),
                ("booking_opens_at", models.DateTimeField(blank=True, null=True)),
                ("booking_closes_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deposit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Charged today when a guest chooses a payment plan.",
                        max_digits=8,
                    ),
                ),
                (
                    "final_payment_due_date",
                    models.DateField(
                        blank=True,
                        help_text="The last instalment of a payment plan lands on this date.",
                        null=True,
                    ),
                ),
                (
                    "plan_cutoff_days",
                    models.PositiveSmallIntegerField(
                        default=60,
                        help_text="Payment plans are offered only this many days or more before departure.",
                    ),
                ),
                ("cancellation_policy", models.TextField(blank=True)),
                (
                    "notes_for_staff",
                    models.TextField(blank=True, help_text="Never shown to guests."),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="departures",
                        to="catalog.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="TripImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="trips/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="DeparturePickup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("boarding_time", models.TimeField()),
                (
                    "seats_available",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Leave blank when the stop has no separate limit.",
                        null=True,
                    ),
                ),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "departure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pickups",
                        to="catalog.departure",
                    ),
                ),
                (
                    "pickup_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pickups",
                        to="catalog.pickuppoint",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "boarding_time"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("departure", "pickup_point"),
                        name="unique_pickup_per_departure",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PriceOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="e.g. Double occupancy, Child (under 12)",
                        max_length=80,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "departure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_options",
                        to="catalog.departure",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "amount"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("departure", "label"),
                        name="unique_price_label_per_departure",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("amount__gte", 0)),
                        name="price_not_negative",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ItineraryDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_number", models.PositiveSmallIntegerField()),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itinerary_days",
                        to="catalog.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["day_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("trip", "day_number"), name="unique_day_per_trip"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="departure",
            index=models.Index(
                fields=["status", "start_date"], name="catalog_dep_status_f8cd9a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="departure",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gte", models.F("start_date"))),
                name="departure_ends_after_it_starts",
            ),
        ),
        migrations.AddConstraint(
            model_name="departure",
            constraint=models.CheckConstraint(
                condition=models.Q(("capacity__gte", 1)), name="departure_has_capacity"
            ),
        ),
        migrations.AddConstraint(
            model_name="departure",
            constraint=models.CheckConstraint(
                condition=models.Q(("deposit_amount__gte", 0)),
                name="departure_deposit_not_negative",
            ),
        ),
    ]
