# Generated by Django 5.2.17 on 2026-09-22 18:57

import apps.core.images
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "slot",
                    models.CharField(
                        choices=[
                            ("home_hero", "Home page banner"),
                            ("day_trip", "Category: Day trip"),
                            ("overnight", "Category: Overnight tour"),
                            ("theatre", "Category: Theatre coach"),
                            ("luncheon", "Category: Luncheon show"),
                            ("cruise", "Category: Cruise"),
                            ("fly", "Category: Fly tour"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="A JPEG, PNG or WebP photo, landscape, at least 1600 pixels wide for the sharpest result. It is resized automatically and its location data is removed.",
                        upload_to="site/",
                        validators=[apps.core.images.validate_image_upload],
                        verbose_name="photo",
                    ),
                ),
                (
                    "image_card",
                    models.ImageField(
                        blank=True, editable=False, upload_to="site/cards/"
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        help_text="Describe the photo in a few words for people using screen readers, e.g. 'The Breakers mansion seen from the lawn'.",
                        max_length=200,
                        verbose_name="description",
                    ),
                ),
            ],
            options={
                "verbose_name": "site photo",
                "ordering": ["slot"],
            },
        ),
        migrations.AlterModelOptions(
            name="tripimage",
            options={
                "ordering": ["display_order", "id"],
                "verbose_name": "gallery photo",
            },
        ),
        migrations.AddField(
            model_name="trip",
            name="hero_image_alt",
            field=models.CharField(
                blank=True,
                help_text="Describe the photo in a few words for people using screen readers, e.g. 'The Breakers mansion seen from the lawn'.",
                max_length=200,
                verbose_name="main photo description",
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="hero_image_card",
            field=models.ImageField(
                blank=True, editable=False, upload_to="trips/cards/"
            ),
        ),
        migrations.AddField(
            model_name="tripimage",
            name="alt_text",
            field=models.CharField(
                blank=True,
                help_text="Describe the photo in a few words for people using screen readers, e.g. 'The Breakers mansion seen from the lawn'.",
                max_length=200,
                verbose_name="description",
            ),
        ),
        migrations.AddField(
            model_name="tripimage",
            name="image_card",
            field=models.ImageField(
                blank=True, editable=False, upload_to="trips/cards/"
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="hero_image",
            field=models.ImageField(
                blank=True,
                help_text="A JPEG, PNG or WebP photo, landscape, at least 1600 pixels wide for the sharpest result. It is resized automatically and its location data is removed. Shown at the top of the trip page and on listings.",
                upload_to="trips/",
                validators=[apps.core.images.validate_image_upload],
                verbose_name="main photo",
            ),
        ),
        migrations.AlterField(
            model_name="tripimage",
            name="caption",
            field=models.CharField(
                blank=True,
                help_text="Optional line shown under the photo.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="tripimage",
            name="image",
            field=models.ImageField(
                help_text="A JPEG, PNG or WebP photo, landscape, at least 1600 pixels wide for the sharpest result. It is resized automatically and its location data is removed.",
                upload_to="trips/",
                validators=[apps.core.images.validate_image_upload],
                verbose_name="photo",
            ),
        ),
    ]
