# Generated by Django 5.2.17 on 2026-09-23 01:23

import apps.core.images
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_trip_photos"),
    ]

    operations = [
        migrations.CreateModel(
            name="SitePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("terms", "Booking terms and conditions"),
                            ("privacy", "Privacy policy"),
                            ("contact", "Contact us"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                (
                    "body",
                    models.TextField(
                        help_text="Plain text. Leave a blank line between paragraphs. Start a line with '## ' for a heading, or '- ' for a bullet point. Web addresses become links."
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Tick once the page is accurate for your business. Guests see nothing until then.",
                        verbose_name="published",
                    ),
                ),
            ],
            options={
                "verbose_name": "site page",
                "ordering": ["kind"],
            },
        ),
        migrations.CreateModel(
            name="SiteText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "home_headline",
                    models.CharField(
                        blank=True,
                        help_text="Shown large on the home page banner, e.g. 'Leave the driving to us.'",
                        max_length=80,
                        verbose_name="home page headline",
                    ),
                ),
                (
                    "home_headline_accent",
                    models.CharField(
                        blank=True,
                        help_text="Shown after the headline in the accent colour, e.g. 'Enjoy the journey.'",
                        max_length=80,
                        verbose_name="headline, second part",
                    ),
                ),
                (
                    "home_intro",
                    models.TextField(
                        blank=True,
                        help_text="One or two sentences under the headline.",
                        max_length=400,
                        verbose_name="home page introduction",
                    ),
                ),
                (
                    "footer_about",
                    models.TextField(
                        blank=True,
                        help_text="A sentence or two about the business, shown at the foot of every page.",
                        max_length=400,
                        verbose_name="about us, in the footer",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="A square logo or emblem, PNG with a transparent background works best, at least 96 pixels across. Shown beside the business name.",
                        upload_to="brand/",
                        validators=[apps.core.images.validate_logo_upload],
                    ),
                ),
            ],
            options={
                "verbose_name": "site text and logo",
                "verbose_name_plural": "site text and logo",
            },
        ),
    ]
